nohup: ignoring input
[2025-06-28 15:28:05 +0000] [28022] [INFO] Starting gunicorn 23.0.0
[2025-06-28 15:28:05 +0000] [28022] [INFO] Listening at: http://0.0.0.0:8000 (28022)
[2025-06-28 15:28:05 +0000] [28022] [INFO] Using worker: sync
[2025-06-28 15:28:05 +0000] [28025] [INFO] Booting worker with pid: 28025
[2025-06-28 15:28:05 +0000] [28027] [INFO] Booting worker with pid: 28027
[2025-06-28 15:28:05 +0000] [28025] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/lebenskompass-api/lebenskompass-api/app.py", line 2, in <module>
    from google_sheets import read_sheet_values
  File "/root/lebenskompass-api/lebenskompass-api/google_sheets.py", line 2, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'
[2025-06-28 15:28:05 +0000] [28025] [INFO] Worker exiting (pid: 28025)
[2025-06-28 15:28:05 +0000] [28028] [INFO] Booting worker with pid: 28028
[2025-06-28 15:28:05 +0000] [28027] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/lebenskompass-api/lebenskompass-api/app.py", line 2, in <module>
    from google_sheets import read_sheet_values
  File "/root/lebenskompass-api/lebenskompass-api/google_sheets.py", line 2, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'
[2025-06-28 15:28:05 +0000] [28027] [INFO] Worker exiting (pid: 28027)
[2025-06-28 15:28:05 +0000] [28022] [ERROR] Worker (pid:28025) exited with code 3
[2025-06-28 15:28:05 +0000] [28022] [ERROR] Worker (pid:28027) was sent SIGTERM!
[2025-06-28 15:28:05 +0000] [28028] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/lebenskompass-api/lebenskompass-api/app.py", line 2, in <module>
    from google_sheets import read_sheet_values
  File "/root/lebenskompass-api/lebenskompass-api/google_sheets.py", line 2, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'
[2025-06-28 15:28:05 +0000] [28028] [INFO] Worker exiting (pid: 28028)
[2025-06-28 15:28:05 +0000] [28022] [ERROR] Worker (pid:28028) exited with code 3
Traceback (most recent call last):
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 208, in run
    self.sleep()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 359, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
    self.reap_workers()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 529, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/lebenskompass-api/lebenskompass-api/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 66, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 235, in run
    super().run()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 228, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 341, in halt
    self.stop()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 395, in stop
    time.sleep(0.1)
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
    self.reap_workers()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 529, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2025-06-28 15:39:30 +0000] [28411] [INFO] Starting gunicorn 23.0.0
[2025-06-28 15:39:30 +0000] [28411] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-06-28 15:39:30 +0000] [28411] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-06-28 15:39:31 +0000] [28411] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-06-28 15:39:31 +0000] [28411] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-06-28 15:39:32 +0000] [28411] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-06-28 15:39:32 +0000] [28411] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-06-28 15:39:33 +0000] [28411] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-06-28 15:39:33 +0000] [28411] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-06-28 15:39:34 +0000] [28411] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-06-28 15:39:34 +0000] [28411] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-06-28 15:39:35 +0000] [28411] [ERROR] Can't connect to ('0.0.0.0', 8000)
[2025-06-29 05:41:10 +0000] [37284] [INFO] Starting gunicorn 23.0.0
[2025-06-29 05:41:10 +0000] [37284] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-06-29 05:41:10 +0000] [37284] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-06-29 05:41:11 +0000] [37284] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-06-29 05:41:11 +0000] [37284] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-06-29 05:41:12 +0000] [37284] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-06-29 05:41:12 +0000] [37284] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-06-29 05:41:13 +0000] [37284] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-06-29 05:41:13 +0000] [37284] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-06-29 05:41:14 +0000] [37284] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-06-29 05:41:14 +0000] [37284] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-06-29 05:41:15 +0000] [37284] [ERROR] Can't connect to ('0.0.0.0', 8000)
[2025-06-29 05:54:38 +0000] [37824] [INFO] Starting gunicorn 23.0.0
[2025-06-29 05:54:38 +0000] [37824] [INFO] Listening at: http://0.0.0.0:8000 (37824)
[2025-06-29 05:54:38 +0000] [37824] [INFO] Using worker: sync
[2025-06-29 05:54:38 +0000] [37828] [INFO] Booting worker with pid: 37828
[2025-06-29 05:54:38 +0000] [37829] [INFO] Booting worker with pid: 37829
[2025-06-29 05:54:38 +0000] [37830] [INFO] Booting worker with pid: 37830
[2025-06-29 06:32:10 +0000] [37829] [INFO] Parent changed, shutting down: <Worker 37829>
[2025-06-29 06:32:10 +0000] [37829] [INFO] Worker exiting (pid: 37829)
[2025-06-29 06:32:10 +0000] [37830] [INFO] Parent changed, shutting down: <Worker 37830>
[2025-06-29 06:32:10 +0000] [37830] [INFO] Worker exiting (pid: 37830)
[2025-06-29 08:15:50 +0000] [46205] [INFO] Starting gunicorn 23.0.0
[2025-06-29 08:15:50 +0000] [46205] [INFO] Listening at: http://0.0.0.0:8000 (46205)
[2025-06-29 08:15:50 +0000] [46205] [INFO] Using worker: sync
[2025-06-29 08:15:50 +0000] [46209] [INFO] Booting worker with pid: 46209
[2025-06-29 08:15:51 +0000] [46210] [INFO] Booting worker with pid: 46210
[2025-06-29 08:15:51 +0000] [46209] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/lebenskompass-api/lebenskompass-api/app.py", line 2, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
[2025-06-29 08:15:51 +0000] [46209] [INFO] Worker exiting (pid: 46209)
[2025-06-29 08:15:51 +0000] [46205] [ERROR] Worker (pid:46209) exited with code 3
[2025-06-29 08:15:51 +0000] [46210] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/lebenskompass-api/lebenskompass-api/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/lebenskompass-api/lebenskompass-api/app.py", line 2, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
[2025-06-29 08:15:51 +0000] [46210] [INFO] Worker exiting (pid: 46210)
[2025-06-29 08:15:51 +0000] [46205] [ERROR] Worker (pid:46210) exited with code 3
